hdv_admin_news_home:
    path:     /news
    defaults: { _controller: HDVAdminBundle:News:index }

hdv_admin_news_grid:
    path:     /gridnews
    defaults: { _controller: HDVAdminBundle:News:grid }

hdv_admin_add_news:
    path:     /news/add
    defaults: { _controller: HDVAdminBundle:News:addnews }

hdv_admin_news_edit:
    path:      /news/edit/{news}
    defaults:
        _controller: HDVAdminBundle:News:editnews
    requirements:
        news: \d+

hdv_admin_news_delete:
    path:      /news/delete/{news}
    defaults:
        _controller: HDVAdminBundle:News:deletenews
    requirements:
        news: \d+
