auction_one_main:
    resource: "@AuctionOneMainBundle/Controller/"
    type:     annotation
    prefix:   /pro

hdv_mobile:
    resource: "@HDVMobileBundle/Controller/"
    type:     annotation
    prefix:   /mobile

hdv_admin:
    resource: "@HDVAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

hdv_admin_news:
    resource: "@HDVAdminBundle/Resources/config/routing_news.yml"
    prefix:   /admin

hdv_admin_estimate:
    resource: "@HDVAdminBundle/Resources/config/routing_estimate.yml"
    prefix:   /admin

hdv_ventes:
    resource: "@HDVVentesBundle/Resources/config/routing.yml"
    prefix:   /ventes

hdv_main:
    resource: "@HDVMainBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
