# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.filter.carousel:
        class: HDV\MainBundle\Imagine\Filter\Loader\Carousel
        tags:
            - { name: "liip_imagine.filter.loader", loader: carousel }
    app.form.registration:
        class: HDV\UserBundle\Form\RegistrationFormType
    app.form.profile:
        class: HDV\UserBundle\Form\ProfileFormType
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    import.csvtoarray:
        class: HDV\MainBundle\Services\ConvertCsvToArray
    Encrypt.Decrypt:
        class: HDV\MainBundle\Services\EncryptDecrypt
    imagesmultiple.twig_extension:
        class: HDV\VentesBundle\Twig\ImagesmultipleExtension
        arguments: ['@twig']
        tags:
            - { name: twig.extension }
    substrdatatables.twig_extension:
        class: HDV\VentesBundle\Twig\SubstrDatatablesExtension
        arguments: ['@twig', '@service_container']
        tags:
            - { name: twig.extension }
    decryptage.twig_extension:
        class: HDV\AdminBundle\Twig\DecryptageExtension
        arguments: ['@twig']
        tags:
            - { name: twig.extension }
    admin.mailer:
      class: HDV\AdminBundle\Services\Mailer
      arguments: ['@mailer','@templating']
    main.fileuploader:
        class: HDV\MainBundle\Services\FileUploader
        arguments: [ '@doctrine.orm.entity_manager', '@request_stack', '@validator', '@kernel' ]
