<?php

namespace HDV\MainBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * EstimateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimateRepository extends \Doctrine\ORM\EntityRepository
{

   public function getAllEstimates()
    {
      $qb = $this->createQueryBuilder('e')
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }

    public function getMesEstims($userid, $page, $nbPerPage)
    {
      $query = $this->createQueryBuilder('e')
        ->where('e.user = :userid')
        ->setParameter('userid', $userid)
        ->orderBy('e.date', 'DESC')
        ->getQuery()
      ;

      $query
        // On définit l'annonce à partir de laquelle commencer la liste
        ->setFirstResult(($page-1) * $nbPerPage)
        // Ainsi que le nombre d'annonce à afficher sur une page
        ->setMaxResults($nbPerPage)
      ;

      // Enfin, on retourne l'objet Paginator correspondant à la requête construite
      // (n'oubliez pas le use correspondant en début de fichier)
      return new Paginator($query, true);
    }

}
