<?php

namespace HDV\VentesBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * VentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentesRepository extends \Doctrine\ORM\EntityRepository
{

  public function getVentesfutur()
   {
     $qb = $this->createQueryBuilder('v')
       ->where('v.date > :datecourant')
       ->setParameter('datecourant', new \Datetime('now'))
       ->orderBy('v.date', 'ASC')
     ;

     return $qb
       ->getQuery()
       ->getResult()
     ;
   }

   public function getVentesold()
    {
      $qb = $this->createQueryBuilder('v')
        ->where('v.date < :datecourant')
        ->setParameter('datecourant', new \Datetime('now'))
        ->orderBy('v.date', 'DESC')
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }


   public function getVentesfuturmenu()
    {
      $qb = $this->createQueryBuilder('v')
        ->where('v.date > :datecourant')
        ->setParameter('datecourant', new \Datetime('now'))
        ->orderBy('v.date', 'ASC')
        ->setMaxResults(5)
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }

}
