<?php

namespace HDV\UserBundle\Repository;

/**
 * BaccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaccountRepository extends \Doctrine\ORM\EntityRepository
{
}
